# Generated by Django 3.1.1 on 2020-09-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200908_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='place',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='star_cast',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
